### ISSUE TITLE
vulkan validation errors + panic

### ISSUE THREAD

**Issue by rukai** [hecrj/wgpu_glyph#8]
After adding wgpu_glyph to my application everything works fine.
However once when running, I got these repeating validation errors:
```
ERROR gfx_backend_vulkan 
VALIDATION [VUID-VkBufferImageCopy-imageOffset-00197 (0)] : vkCmdCopyBufferToImage(): Both pRegion[0] imageoffset.x (264) and (imageExtent.width + imageOffset.x) (312) must be >= zero or <= image subresource width (256). The Vulkan spec states: imageOffset.x and (imageExtent.width + imageOffset.x) must both be greater than or equal to 0 and less than or equal to the image subresource width (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkBufferImageCopy-imageOffset-00197)
object info: (type: IMAGE, hndl: 22)

ERROR gfx_backend_vulkan 
VALIDATION [VUID-vkCmdCopyBufferToImage-pRegions-00172 (0)] : vkCmdCopyBufferToImage(): pRegion[0] exceeds image bounds.. The Vulkan spec states: The image region specified by each element of pRegions must be a region that is contained within dstImage (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdCopyBufferToImage-pRegions-00172)
object info: (type: COMMAND_BUFFER, hndl: 0)
```

And then it panicked with:
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `Ok(false)`,
 right: `Ok(true)`: GPU got stuck on a frame (image 1) :(', /home/rubic/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/dbef9f3/wgpu-native/src/swap_chain.rs:178:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: wgpu_swap_chain_get_next_texture
  10: wgpu::SwapChain::get_next_texture
  11: pf_sandbox::wgpu::WgpuGraphics::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Illegal instruction (core dumped)
```

I believe this was caused by wgpu_glyph as my application does not copy buffers to images, but wgpu_glyph does.

**Comment by hecrj** [comment]
This should be related to #7. Check the fix in #9!
